services:
  testlasmartv2:
    image: testlasmartv2
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5050:8080"
      - "5051:8081"
    volumes:
      - ./wwwroot:/app/wwwroot

